### ISSUE TITLE
Release tests

### ISSUE THREAD

**Issue by fabaff** [orf/xpath-expressions#3]
It would help if the tests would be part of the source tarball published on PyPI. Then distributions would run the tests during the build process.

Tagging the source would create a releases on GitHub. Those tarballs would contain the tests directory. If you don't want to add them to the source tarball for PyPI.

Thanks.

**Comment by orf** [comment]
I'm not sure about adding tests to the source release, but I've started tagging the releases (https://github.com/orf/xpath-expressions/releases/tag/v1.1.0) that include the full tarball. Is that ok?

**Comment by fabaff** [comment]
Works. Thanks
